"""initial

Revision ID: 76becf50ef06
Revises: 
Create Date: 2026-03-03 13:17:03.926617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76becf50ef06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
